name: Lint Awesome List
on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:
  awesome-lint:
    name: "lint: awesome-lint"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
      - name: Test awesome-lint
        uses: max/awesome-lint@v2.0.0
