name: Lint Awesome List
on:
  push:
  pull_request:

jobs:
  awesome-lint:
    name: "lint: awesome-lint"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0
      - name: Test awesome-lint with custom file path
        uses: jthegedus/github-action-awesome-lint@0.1.0
